### ISSUE TITLE
目录结构有点看不懂

### ISSUE THREAD

**Issue by kwzm** [umijs/umi-dva-user-dashboard#4]
通过dva-cli生成的目录结构里src下层有models、services，但是为何又要在page/users下面创建models和services呢？

**Comment by xiaohuoni** [comment]
外面的是全局加载的，里面的是为了做按需加载

**Comment by kwzm** [comment]
哦哦，原来是这样，希望dva-cli1.0出正式版之后能写一个文档专门介绍文件目录结构。

**Comment by xiaohuoni** [comment]
目录结构是在约定的基础上自己修改的。大致的目录可以参考https://github.com/xiaohuoni/dva-umi/blob/master/README.md 这个里面的目录结构说明

**Comment by kwzm** [comment]
好的，感谢！
